version: '3.8'

services:
  naberesh:
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    container_name: naberesh-app
    restart: unless-stopped
    ports:
      - "824:824"
